const assert=require('node:assert/strict');
const C=require('../www/collaboration-core.js');
let counter=0;const uuid=()=>`operation-${++counter}`;
const order={id:'C1',name:'Prueba',rows:[{id:1,qty:3}],images:{front:null,back:null},dataOk:false,confirmed:false,designOk:false,paymentOk:false,startDate:'',released:false,sewn:false,packed:false,shipped:false,delivered:false,contact:''};
const state={orders:[structuredClone(order)],basePrice:800,cutPrice:10,rates:[],shortCosts:{},issuer:{},calendar:{saturday:false,extra:''},isrControl:{},designs:[]};
let meta={role:'admin',bases:{C1:{data:structuredClone(order),version:1}},settingsBase:{data:C.settings(state),version:1},pending:{},conflicts:{}};
assert.equal(Object.keys(C.prepare(meta,state,uuid).pending).length,0,'Navigation without edits never queues a cloud write');
state.orders[0].contact='Cliente';let next=C.prepare(meta,state,uuid);assert.equal(next.pending.C1.patch.contact,'Cliente');assert.equal(next.pending.C1.expected.contact,'');
const stable=C.prepare(next,state,uuid);assert.equal(stable.pending.C1.operationId,next.pending.C1.operationId,'A retry retains its operation ID');
state.orders[0].contact='Cliente nuevo';const newer=C.prepare(stable,state,uuid);assert.notEqual(newer.pending.C1.operationId,stable.pending.C1.operationId,'New edits cannot reuse an in-flight operation ID');
const server={...order,sewn:true},local={...order,contact:'Cambio local'};const merged=C.rebase(local,order,server);assert.equal(merged.contact,'Cambio local');assert.equal(merged.sewn,true,'An unrelated remote edit does not erase the local draft');
const ack=C.rebase({...local,contact:'Cambio posterior'},local,{...local,sewn:true});assert.equal(ack.contact,'Cambio posterior');assert.equal(ack.sewn,true,'Acknowledgement preserves edits made while the request was in flight');
state.orders[0].images.front='nuevo diseño';next=C.prepare(meta,state,uuid);assert.equal(next.pending.C1.guards.sewn,false,'A design change checks concurrent production progress before resetting it');
const stored=JSON.parse(JSON.stringify(next));assert.equal(stored.pending.C1.desired.images.front,'nuevo diseño','An offline outbox contains the complete recoverable local copy');
const dep={...meta,role:'costura',userId:'test-user',events:[],displayName:'Costura',settingsBase:{data:{calendar:state.calendar},version:1}};const view=C.stateFrom({...state,revisions:[{quote:'private'}],jobs:[],exportsMade:[]},dep);assert.equal(view.basePrice,0);assert.deepEqual(view.rates,[]);assert.deepEqual(view.revisions,[],'Department caches contain no financial document archive');
function jsonb(value){if(Array.isArray(value))return value.map(jsonb);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().reverse().map(k=>[k,jsonb(value[k])]));return value;}
const fresh={...structuredClone(state),expenses:[],orders:[structuredClone(order)]},fromServer={...meta,bases:{C1:{data:jsonb(order),version:1}},settingsBase:{data:jsonb(C.settings(fresh)),version:1}};
assert.equal(C.equal(order,jsonb(order)),true,'JSONB key order does not represent a data change');
assert.equal(Object.keys(C.prepare(fromServer,fresh,uuid).pending).length,0,'A real JSONB round trip never creates an endless settings outbox');
assert.equal(C.equal([{x:1},{x:2}],[{x:2},{x:1}]),false,'Array order still matters for print lists');
assert.equal(C.equal({x:1,images:{front:'a',back:'b'}},{images:{back:'c',front:'a'},x:1}),false,'An image change is detected despite reordered keys');
assert.deepEqual(view.expenses,[],'Departments receive no expense records');
const normalized={...structuredClone(fresh),orders:[{...structuredClone(order),additionalDesigns:[]}]};
assert.equal(Object.keys(C.prepare(fromServer,normalized,uuid).pending).length,0,'Upgrading old orders does not enqueue empty design arrays');
const upgraded=C.stateFrom(normalized,{...fromServer,userId:'test-user',displayName:'Test'});
assert.deepEqual(upgraded.orders[0].additionalDesigns,[],'Cloud snapshots normalize optional designs before comparing the screen');
const designPatch=C.prepare(fromServer,{...fresh,orders:[{...order,additionalDesigns:[{id:'D-test',name:'Azul',images:{front:'a',back:'b'}}]}]},uuid).pending.C1;
assert.equal(designPatch.guards.sewn,false,'Additional artwork protects concurrent department progress');
assert.equal(C.guardsFor({released:true},order).additionalDesigns,null,'An old order guard preserves its missing-field representation');
const defaults=C.normalizeOrder(order);
assert.equal(Object.keys(C.prepare(fromServer,{...fresh,orders:[defaults]},uuid).pending).length,0,'Old cloud orders never acquire empty quotation fields during navigation');
assert.deepEqual(C.stateFrom({...fresh,orders:[defaults]},fromServer).orders[0].shippingQuote,{amount:0,description:''},'Shipping defaults are normalized before screen equality checks');
const discarded=C.prepare(fromServer,{...fresh,orders:[{...defaults,quoteStatus:'discarded'}]},uuid).pending.C1;
assert.equal(discarded.guards.payments,null,'Discard checks payments added concurrently by another computer');
assert.equal(discarded.guards.advanceRecord,null,'Discard checks a concurrent advance validation');
assert.equal(C.guardsFor({released:true},order).quoteStatus,null,'Production cannot progress after a concurrent quote discard');
assert.equal(C.guardsFor({released:true},order).shippingQuote,null,'Production checks the quotation shipping charge');
assert.deepEqual(C.guardsFor({plannedCosts:{fabric:100}},order),{},'Internal forecast costs do not reset production or payment approvals');
console.log('Synchronization rules: 26 checks passed');
