const {chromium}=require('playwright'),{spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const checks=[],ok=(name,value)=>{assert(value,name);checks.push(name);};
(async()=>{
 const port=4397,server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port)}});await new Promise(r=>server.stdout.once('data',r));let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.PROWAY_CHROME});const context=await browser.newContext({viewport:{width:390,height:1100},acceptDownloads:true,serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:'+port);await page.locator('[data-action="new-order"]').waitFor();await page.locator('#pia-team').waitFor();
  async function saved(){await page.evaluate(()=>ProwayPlatform.flush());return page.evaluate(()=>new Promise(resolve=>{const q=indexedDB.open('proway-pedidos',1);q.onsuccess=()=>{const db=q.result,r=db.transaction('snapshots').objectStore('snapshots').get('current');r.onsuccess=()=>{resolve(r.result.state);db.close();};};}));}
  async function restore(state){await page.locator('[data-screen="tablas"]').click();await page.locator('[data-table="respaldo"]').click();await page.locator('#pia-restore-file').setInputFiles({name:'legacy-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(state))});await page.locator('[data-action="restore-data"]').click();}
  async function download(selector,file){const wait=page.waitForEvent('download');await page.locator(selector).click();const d=await wait;await d.saveAs(path.join(out,file));return d;}
  async function leftMenu(width){await page.setViewportSize({width,height:1100});const a=await page.locator('.pia-side-menu').boundingBox(),b=await page.locator('.pia-work-content').boundingBox();return a.x+a.width<=b.x+1&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);}
  const old=await saved();old.appVersion='1.2.0';const row=(id,product,cut,qty,name)=>({id,product,size:'M',cut,qty,printed:name,color:'Azul',design:'Azul',placement:'Espalda',special:''});
  for(const o of old.orders)delete o.additionalDesigns;
  old.orders[0].name='Prueba Sonora';old.orders[0].rows=[row(1,'Butarga','Hombre',10,'LUIS MONTES')];old.orders[0].payerType='PF';old.orders[0].showVat=false;
  old.orders[1].name='Prueba Jaguares';old.orders[1].rows=[row(2,'Playera','Mujer',11,'ANA PÉREZ')];old.orders[2].rows=[row(3,'Short','Mujer',5,'OTRO CLIENTE')];
  old.expenses=[{id:'E-test',category:'Hilos',date:'2026-10-09',amount:100,client:'',note:'Prueba'}];const untouched=structuredClone(old.orders[1]);
  await restore(old);let current=await saved();ok('Old backups keep every order and garment',current.orders.length===5&&current.orders[0].rows[0].qty===10&&current.orders[1].rows[0].qty===11&&current.orders.every(o=>Array.isArray(o.additionalDesigns)));
  const expected={'rojo-front.png':'1582d7eef71fd879dc25ccb16533c250ee9c85888f36ca8a16314f2a12156c61','rojo-back.png':'6866a12720aad9722b15e1c02a81fbb31833c73c6f9eeeaea6c8d6122daa6ab8','azul-front.png':'ef2a714560a8ac545edc4b6b0b05d807ee39bfc881ee95fc1d459302ee1eeb7b','azul-back.png':'6c19e40c722eef762afec258247d5a1d6a2fee8faa0b8a865990499acb2270c0'};
  ok('All four catalogue images are the unchanged customer originals',Object.entries(expected).every(([file,sha])=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'www/designs',file))).digest('hex')===sha));
  await page.locator('[data-screen="pedido"]').click();await page.locator('summary').filter({hasText:'Tus diseños'}).click();
  ok('Catalogue uses the supplied PNG views instead of generated SVG samples',(await page.locator('.pia-design-catalog img').evaluateAll(images=>images.every(i=>i.getAttribute('src').endsWith('.png'))))&&await page.locator('.pia-garment').count()===0);
  await page.locator('[data-design-use="rojo"]').click();await page.waitForFunction(()=>document.getElementById('pia-feedback').textContent.includes('diseño principal'));current=await saved();
  ok('Selected images preserve the original portrait proportions',await page.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();return i.naturalWidth===800&&i.naturalHeight===1200;},current.orders[0].images.front));
  await page.locator('[data-screen="cobro"]').click();await page.locator('summary').filter({hasText:'Tus diseños'}).click();await page.locator('[data-design-add="azul"]').click();await page.locator('[data-design-name]').waitFor();
  await page.locator('[data-design-name]').fill('Azul competición');await page.locator('[data-design-name]').press('Tab');current=await saved();
  ok('A quotation stores another named front/back design',current.orders[0].additionalDesigns.length===1&&current.orders[0].additionalDesigns[0].name==='Azul competición'&&current.orders[0].additionalDesigns[0].images.back.startsWith('data:image/jpeg'));
  ok('Additional designs do not duplicate garments or change the quotation price',current.orders[0].rows[0].qty===10&&(await page.locator('#pia-sale-total').innerText()).includes('8,000.00'));
  await page.locator('[data-design-new]').click();const pending=(await saved()).orders[0].additionalDesigns.at(-1);await page.locator('[data-screen="taller"]').click();await page.locator('[data-work="diseño"]').click();
  ok('An empty additional design prevents production approval',await page.locator('#pia-design-ok').isDisabled());
  await page.locator('#pia-img-'+pending.id+'-front').setInputFiles(path.join(root,'www/designs/azul-front.png'));await page.waitForFunction(id=>Boolean(document.querySelector('[data-order-design="'+id+'"] .pia-art img')),pending.id);current=await saved();
  ok('An additional image uploads from the phone gallery into the correct slot',current.orders[0].additionalDesigns.at(-1).images.front.startsWith('data:image/jpeg')&&current.orders[0].additionalDesigns[0].images.back);
  await page.locator('[data-design-remove="'+pending.id+'"]').click();ok('Removing an extra design retains the primary and other designs',(await saved()).orders[0].additionalDesigns.length===1&&(await saved()).orders[0].images.front);
  for(const area of ['diseño','costura','empaque']){await page.locator('[data-work="'+area+'"]').click();ok('Both designs appear in '+area,await page.locator('.pia-work-content .pia-art img').count()===4&&(area==='diseño'?await page.locator('[data-design-name]').inputValue()==='Azul competición':(await page.locator('.pia-work-content').innerText()).includes('Azul competición')));}
  await page.locator('[data-screen="cobro"]').click();await page.locator('[data-action="preview-document"]').click();ok('Customer preview includes all four views and the additional name',await page.locator('.pia-quote-design img').count()===4&&(await page.locator('.pia-quote-modern').innerText()).includes('Azul competición'));
  for(const width of [320,390,1024])ok('Export submenu stays on the left and fits at '+width+'px',await leftMenu(width));await page.setViewportSize({width:390,height:1100});
  await page.screenshot({path:path.join(out,'multiple-designs-quote-mobile.png'),fullPage:true});await download('[data-action="run-export"]','multiple-designs-quote.pdf');await page.locator('[data-format="excel"]').click();await download('[data-action="run-export"]','multiple-designs-quote.xlsx');
  const workbook=await page.evaluate(async bytes=>{const wb=new ExcelJS.Workbook();await wb.xlsx.load(new Uint8Array(bytes));const s=wb.getWorksheet('Diseño');return {images:s.getImages().length,values:JSON.stringify(s.getSheetValues())};},Array.from(fs.readFileSync(path.join(out,'multiple-designs-quote.xlsx'))));
  ok('Editable Excel contains four embedded design images and both names',workbook.images===4&&workbook.values.includes('Diseño principal')&&workbook.values.includes('Azul competición'));
  const quote=(await saved()).revisions.filter(r=>r.source==='cotizacion').at(-1).quote;
  const sharedContext=await browser.newContext({viewport:{width:390,height:1100},serviceWorkers:'block'});await sharedContext.route('https://app.proway.test/**',route=>{const u=new URL(route.request().url()),file=path.join(root,'www',u.pathname==='/'?'index.html':u.pathname),types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'};return route.fulfill({body:fs.readFileSync(file),contentType:types[path.extname(file)]||'application/octet-stream'});});
  const client=await sharedContext.newPage();client.on('pageerror',e=>errors.push(e.message));await client.goto('https://app.proway.test/');await client.locator('[data-action="new-order"]').waitFor();const link=await client.evaluate(q=>ProwayPlatform.quoteLink(q,2,'2026-10-09T18:00:00Z'),quote);await client.goto(link);await client.locator('.pia-quote-modern').waitFor();
  ok('Client link retains every design without internal workshop data',await client.locator('.pia-quote-design img').count()===4&&(await client.locator('.pia-quote-modern').innerText()).includes('Azul competición')&&!(await client.locator('#pia-main').innerText()).includes('Hilos'));
  ok('Shared quotation snapshots remain within the supported link size',link.split('#cot=')[1].length<=20000);await client.screenshot({path:path.join(out,'multiple-designs-client-mobile.png'),fullPage:true});await sharedContext.close();
  await page.locator('[data-action="close-document"]').click();await page.locator('[data-screen="taller"]').click();await page.locator('[data-work="etiquetas"]').click();await page.locator('[data-labels-order="C2"]').check();
  ok('Two clients combine into 21 labels on one A4 sheet',(await page.locator('#pia-labels-total').innerText())==='21'&&(await page.locator('#pia-labels-orders').innerText())==='2'&&(await page.locator('#pia-labels-sheets').innerText())==='1');
  const labelFile=await download('[data-labels-action="pdf"]','multi-client-labels.pdf');ok('Batch label filename identifies both clients',labelFile.suggestedFilename().includes('Prueba-Sonora-Prueba-Jaguares'));
  await download('[data-labels-action="excel"]','multi-client-labels.xlsx');const labelBook=await page.evaluate(async bytes=>{const wb=new ExcelJS.Workbook();await wb.xlsx.load(new Uint8Array(bytes));const rows=wb.getWorksheet('Documento').getSheetValues().filter(r=>r?.[2]==='Butarga'||r?.[2]==='Playera');return rows.map(r=>[r[1],r[5],r[9],r[10]]);},Array.from(fs.readFileSync(path.join(out,'multi-client-labels.xlsx'))));
  ok('Every label retains its own client folio, piece number and order total',labelBook.length===21&&labelBook[9][0]===10&&labelBook[9][2]==='C1'&&labelBook[9][3]===10&&labelBook[10][0]===1&&labelBook[10][2]==='C2'&&labelBook[20][0]===11&&labelBook[20][3]===11);
  await page.locator('#pia-labels-start').selectOption({value:'5'});ok('A partially used sheet reserves its first five positions',(await page.locator('#pia-labels-sheets').innerText())==='2');await download('[data-labels-action="pdf"]','multi-client-labels-offset.pdf');
  await page.locator('[data-labels-action="preview"]').click();ok('PDF preview identifies reserved label positions',await page.locator('.pia-label-used').count()===5);await page.locator('[data-action="close-document"]').click();
  await page.locator('[data-labels-action="none"]').click();ok('Empty selection disables printing',await page.locator('[data-labels-action="pdf"]').isDisabled());await page.locator('[data-labels-action="all"]').click();ok('Select all includes every nonempty order once',(await page.locator('#pia-labels-total').innerText())==='26');
  await page.screenshot({path:path.join(out,'multi-client-labels-mobile.png'),fullPage:true});
  await page.locator('[data-screen="historial"]').click();for(const width of [320,390,1024])ok('History submenu stays on the left and fits at '+width+'px',await leftMenu(width));
  await page.setViewportSize({width:390,height:1100});await page.locator('[data-history="versiones"]').click();ok('Printed batches remain in version history',(await page.locator('.pia-work-content').innerText()).includes('Etiquetas de varios pedidos'));
  const beforeReload=await saved();await page.reload();await page.locator('[data-action="new-order"]').waitFor();current=await saved();
  ok('Restart preserves every additional image and the existing expense ledger',JSON.stringify(current.orders[0].additionalDesigns)===JSON.stringify(beforeReload.orders[0].additionalDesigns)&&JSON.stringify(current.expenses)===JSON.stringify(old.expenses));
  delete current.orders[1].additionalDesigns;ok('Design edits and batch printing leave other orders unchanged',JSON.stringify(current.orders[1])===JSON.stringify(untouched));
  ok('No JavaScript errors in design and batch-label workflows',errors.length===0);fs.writeFileSync(path.join(out,'design-labels-checks.json'),JSON.stringify({passed:checks.length,checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));
 }finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
