const {chromium}=require('playwright'),{spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const checks=[],ok=(name,value)=>{assert(value,name);checks.push(name);};
(async()=>{
 const port=4397,server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port)}});await new Promise(r=>server.stdout.once('data',r));let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.PROWAY_CHROME});const context=await browser.newContext({viewport:{width:390,height:1100},acceptDownloads:true,serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.route('https://app.proway.test/**',route=>{const u=new URL(route.request().url()),f=path.join(root,'www',u.pathname==='/'?'index.html':u.pathname),types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'};return route.fulfill({body:fs.readFileSync(f),contentType:types[path.extname(f)]||'application/octet-stream'});});
  await page.goto('https://app.proway.test/');await page.locator('[data-action="new-order"]').waitFor();
  async function saved(){await page.evaluate(()=>ProwayPlatform.flush());return page.evaluate(()=>new Promise(resolve=>{const q=indexedDB.open('proway-pedidos',1);q.onsuccess=()=>{const db=q.result,r=db.transaction('snapshots').objectStore('snapshots').get('current');r.onsuccess=()=>{resolve(r.result.state);db.close();};};}));}
  async function restore(state){await page.locator('[data-screen="tablas"]').click();await page.locator('[data-table="respaldo"]').click();await page.locator('#pia-restore-file').setInputFiles({name:'old-quote-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(state))});await page.locator('[data-action="restore-data"]').click();}
  async function set(selector,value){await page.locator(selector).fill(String(value));await page.locator(selector).dispatchEvent('change');}
  async function download(selector,file){const wait=page.waitForEvent('download');await page.locator(selector).click();const d=await wait;await d.saveAs(path.join(out,file));return d;}
  async function finance(){await page.locator('[data-screen="tablas"]').click();await page.locator('[data-table="finanzas"]').click();}
  async function book(file){return page.evaluate(async bytes=>{const w=new ExcelJS.Workbook();await w.xlsx.load(new Uint8Array(bytes));return w.worksheets.map(s=>({name:s.name,rows:s.getSheetValues()}));},Array.from(fs.readFileSync(path.join(out,file))));}
  const legacy=await saved(),row=(id,product,cut,qty)=>({id,product,cut,size:'M',qty,printed:'Prueba',color:'Rojo',design:'Rojo',placement:'',special:''});
  for(const o of legacy.orders){delete o.quoteStatus;delete o.shippingQuote;delete o.plannedCosts;delete o.additionalDesigns;}
  legacy.appVersion='1.3.0';legacy.orders[0].name='Prueba Sonora';legacy.orders[0].rows=[row(1,'Butarga','Hombre',2)];legacy.orders[0].payerType='PF';legacy.orders[0].dataOk=true;
  legacy.orders[1].name='Prueba Jaguares';legacy.orders[1].rows=[row(2,'Playera','Mujer',1)];Object.assign(legacy.orders[1],{payerType:'PF',advance:700,advanceDate:'2026-10-09',paymentOk:true,advanceRecord:{date:'2026-10-09',amount:700,retention:0,documented:false,simulated:false}});
  legacy.rates=[{product:'Butarga',size:'M',cut:'Hombre',cost:100},{product:'Playera',size:'M',cut:'Mujer',cost:70}];legacy.expenses=[{id:'E-a',category:'Costura',date:'2026-10-09',amount:100,client:'C1',note:'Test'},{id:'E-b',category:'Hilos',date:'2026-10-09',amount:40,client:'C1',note:'Test'},{id:'E-c',category:'Hilos',date:'2026-10-09',amount:50,client:'',note:'Test'}];
  await restore(legacy);let state=await saved();ok('Upgrade preserves existing order quantities, cash and expenses',state.orders[0].rows[0].qty===2&&state.orders[1].advanceRecord.amount===700&&state.expenses.length===3);ok('Legacy quotes receive compatible empty defaults',state.orders.every(o=>o.quoteStatus==='active'&&o.shippingQuote.amount===0&&o.plannedCosts.shipping===0));
  await page.locator('[data-screen="cobro"]').click();await set('#pia-shipping-amount',232);await set('#pia-shipping-description','Paquetería a domicilio');
  ok('Editable shipping adds to the quotation and its net balance',(await page.locator('#pia-sale-total').innerText()).includes('1,832.00')&&(await page.locator('#pia-main').innerText()).includes('1,832.00'));
  await page.locator('summary').filter({hasText:'Costos y utilidad prevista'}).click();for(const [k,n] of Object.entries({fabric:200,sewing:160,shipping:120,other:20}))await set('#pia-plan-C1-'+k,n);
  ok('Unpaid quotation shows profit excluding sales IVA and known costs',(await page.locator('#pia-order-profit-C1').innerText()).includes('839.31'));
  await page.locator('[data-action="preview-document"]').click();ok('Customer preview shows shipping as its own line',(await page.locator('.pia-doc-quote').innerText()).includes('Envío')&&(await page.locator('.pia-doc-quote').innerText()).includes('232.00'));
  ok('Customer preview does not expose internal shipping cost or profit',!(await page.locator('.pia-quote-modern').innerText()).includes('utilidad')&&!(await page.locator('.pia-quote-modern').innerText()).includes('Costo de envío para Proway'));
  await download('[data-action="run-export"]','quote-shipping.pdf');await page.locator('[data-format="excel"]').click();await download('[data-action="run-export"]','quote-shipping.xlsx');const compact=await book('quote-shipping.xlsx');
  const shipping=compact[0].rows.find(r=>String(r?.[1]).startsWith('Envío'));ok('Excel contains editable shipping and recalculating totals',shipping?.[4]===1&&shipping?.[5]===232&&shipping?.[6].formula.startsWith('ROUND(SUMPRODUCT'));
  ok('Internal forecast costs are absent from customer Excel',!JSON.stringify(compact).includes('plannedCosts')&&!JSON.stringify(compact).includes('Utilidad prevista'));
  await page.locator('[data-action="close-document"]').click();await page.locator('[data-action="share-quote"]').click();await page.locator('[data-action="queue-link"]').click();const link=await page.locator('#pia-quote-url').inputValue();
  const shared=await browser.newContext({viewport:{width:390,height:1100},serviceWorkers:'block'});await shared.route('https://app.proway.test/**',async route=>{const u=new URL(route.request().url()),f=path.join(root,'www',u.pathname==='/'?'index.html':u.pathname);if(!fs.existsSync(f))return route.abort();await route.fulfill({path:f,contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.html')?'text/html':undefined});});const client=await shared.newPage();await client.goto(link.replace('http://localhost:'+port,'https://app.proway.test'));await client.locator('.pia-quote-modern').waitFor();
  ok('Client link retains shipping and the final amount',(await client.locator('.pia-doc-quote').innerText()).includes('Paquetería a domicilio')&&(await client.locator('.pia-quote-modern').innerText()).includes('1,832.00'));await shared.close();
  await page.locator('[data-action="close-document"]').click();await page.locator('#pia-order').selectOption('1');await page.locator('[data-screen="cobro"]').click();await page.locator('summary').filter({hasText:'Costos y utilidad prevista'}).click();await set('#pia-plan-C2-fabric',100);await set('#pia-plan-C2-sewing',100);
  ok('Editing internal forecasts retains validated advance records',(await saved()).orders[1].paymentOk&&(await saved()).orders[1].advanceRecord.amount===700);
  await page.locator('summary').filter({hasText:'Cotización no aprobada'}).click();ok('Already paid work cannot be discarded',await page.locator('[data-action="discard-quote"]').isDisabled());
  await finance();ok('Total expected profit includes unpaid orders and general expenses',(await page.locator('#pia-finance-profit').innerText()).includes('1,198.97'));ok('Expected profit is distinct from actual available cash',(await page.locator('#pia-finance-available').innerText()).includes('510.00')&&(await page.locator('#pia-finance-cash').innerText()).includes('700.00'));
  await download('[data-finance="finance-excel"]','profit-finance.xlsx');await download('[data-finance="finance-pdf"]','profit-finance.pdf');const fb=await book('profit-finance.xlsx');ok('Finance exports contain per-client and overall expected profit',JSON.stringify(fb).includes('1198.97')&&JSON.stringify(fb).includes('Utilidad antes de ISR')&&fb.some(s=>s.name==='Totales por cliente'));
  await page.locator('#pia-order').selectOption('0');await page.locator('[data-screen="cobro"]').click();await page.locator('summary').filter({hasText:'Cotización no aprobada'}).click();state=await saved();const before=structuredClone(state.orders[0]);await page.locator('[data-action="discard-quote"]').click();state=await saved();
  ok('Discarded quotation retains garments, artwork, prices and shipping',state.orders[0].quoteStatus==='discarded'&&JSON.stringify(state.orders[0].rows)===JSON.stringify(before.rows)&&JSON.stringify(state.orders[0].images)===JSON.stringify(before.images)&&state.orders[0].shippingQuote.amount===232);
  ok('Discarded quotes have a restore action in the left-hand history menu',await page.locator('[data-history="descartadas"][aria-pressed="true"]').count()===1&&await page.locator('[data-restore-quote="C1"]').count()===1);
  await page.locator('[data-screen="cobro"]').click();ok('Archived quote becomes read-only instead of continuing into production',await page.locator('[data-action="restore-quote"]').count()===1&&await page.locator('#pia-shipping-amount').count()===0);
  await finance();ok('Discard removes projected revenue and retains its incurred expenses',(await page.locator('#pia-finance-quoted').innerText()).includes('800.00')&&(await page.locator('#pia-finance-profit').innerText()).includes('219.66'));
  await page.locator('#pia-order').selectOption('1');ok('Discarded quotes leave the active order picker',await page.locator('#pia-order option[value="0"]').count()===0);await page.locator('[data-screen="taller"]').click();await page.locator('[data-work="etiquetas"]').click();await page.locator('[data-labels-action="all"]').click();ok('Batch labels exclude discarded quotations',(await page.locator('#pia-labels-total').innerText())==='1'&&await page.locator('[data-labels-order="C1"]').count()===0);
  await page.locator('[data-screen="tablas"]').click();await page.locator('[data-table="proveedor"]').click();await page.locator('[data-finance="all"]').click();ok('Supplier batches exclude discarded quotes',(await page.locator('#pia-batch-total').innerText()).includes('80.00')&&await page.locator('[data-batch-order="C1"]').count()===0);
  await page.locator('[data-screen="historial"]').click();await page.locator('[data-history="descartadas"]').click();await page.locator('[data-restore-quote="C1"]').click();state=await saved();ok('Restore recovers the same quotation without duplicated capture',state.orders[0].quoteStatus==='active'&&state.orders[0].rows[0].qty===2&&state.orders[0].shippingQuote.amount===232&&state.orders[0].plannedCosts.sewing===160);
  await finance();ok('Restored quotation returns to overall expected profit',(await page.locator('#pia-finance-profit').innerText()).includes('1,198.97'));
  await page.locator('#pia-expense-form [name="category"]').selectOption('Costura');await page.locator('#pia-expense-form [name="client"]').selectOption('C1');await page.locator('#pia-expense-form [name="amount"]').fill('200');await page.locator('#pia-expense-form button').click();ok('An over-budget paid cost replaces its forecast without double counting',(await page.locator('#pia-finance-profit').innerText()).includes('1,058.97')&&(await page.locator('#pia-finance-available').innerText()).includes('310.00'));
  await page.screenshot({path:path.join(out,'expected-profit-mobile.png'),fullPage:true});
  await page.locator('[data-screen="cobro"]').click();await page.locator('#pia-show-vat').check();await page.locator('#pia-vat').selectOption('added');ok('Shipping follows plus-IVA mode',(await page.locator('#pia-sale-total').innerText()).includes('2,125.12'));await page.locator('[data-action="preview-document"]').click();await download('[data-action="run-export"]','quote-shipping-iva.pdf');await page.locator('[data-format="excel"]').click();await download('[data-action="run-export"]','quote-shipping-iva.xlsx');const taxed=await book('quote-shipping-iva.xlsx');ok('Detailed quote Excel retains shipping in its taxable subtotal',taxed[0].rows.some(r=>String(r?.[1]).startsWith('Envío')&&r?.[5]===232)&&taxed[0].rows.some(r=>r?.[1]==='Total antes de retenciones'&&r?.[2].result===2125.12));
  await page.locator('[data-action="close-document"]').click();const beforeReload=await saved();await page.reload();await page.locator('[data-action="new-order"]').waitFor();state=await saved();ok('Restart preserves shipping, budgets, actual cash and all expenses',JSON.stringify(state.orders)===JSON.stringify(beforeReload.orders)&&JSON.stringify(state.expenses)===JSON.stringify(beforeReload.expenses));
  const rounding=structuredClone(state);rounding.orders[0].rows[0].qty=3;rounding.orders[0].rows[0].special=800.01;rounding.orders[0].shippingQuote.amount=0.01;rounding.orders[0].showVat=false;await restore(rounding);await page.locator('[data-screen="cobro"]').click();await page.locator('[data-action="preview-document"]').click();await page.locator('[data-format="excel"]').click();await download('[data-action="run-export"]','quote-rounding.xlsx');const rb=await book('quote-rounding.xlsx'),rr=rb[0].rows.filter(r=>r?.[1]==='Butarga'||String(r?.[1]).startsWith('Envío'));ok('Compact Excel retains precise final unit prices and reconciles shipping rounding',rr[0][5]===928.0116&&rr[1][5]===0.0116&&rr[1][6].result===0.02&&rr[1][6].formula.includes('SUMPRODUCT')&&rb[0].rows.some(r=>r?.[1]==='Total de la cotización'&&r[2].result===2784.05));await page.locator('[data-action="close-document"]').click();
  const edge=await page.evaluate(s=>{const metrics={records:[],orders:s.orders.map(o=>({id:o.id,name:o.name,quantity:o.rows.reduce((n,r)=>n+r.qty,0),total:0,subtotal:0,balance:0}))};s.rates=[];const missing=ProwayFinance.totals(s,metrics);s.orders[0].rows=[{product:'Short',size:'M',cut:'Mujer',qty:2}];s.orders[0].plannedCosts={fabric:0,sewing:0,shipping:0,other:0};s.shortCosts={M:[50,70]};s.expenses=[];const short=ProwayFinance.forecast(s.orders[0],s,1000);s.orders[0].supplier.mode='added';const vat=ProwayFinance.forecast(s.orders[0],s,1000);return {pending:missing.profit===null,shortCost:short.cost,shortProfit:short.profit,supplierVatCost:vat.cost};},state);
  ok('Missing sublimation tariffs keep expected profit pending',edge.pending);ok('Short forecast includes fabric and fixed cutting cost',edge.shortCost===260&&edge.shortProfit===740);ok('Supplier IVA is included conservatively in planned costs',edge.supplierVatCost===285.6);
  for(const width of [320,390,1024]){await page.setViewportSize({width,height:1100});await page.locator('[data-screen="cobro"]').click();ok('Quotation fields fit at '+width+'px',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  ok('Quotation and profit workflows raise no JavaScript errors',errors.length===0);fs.writeFileSync(path.join(out,'quote-profit-checks.json'),JSON.stringify({passed:checks.length,checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));
 }finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
