const {chromium}=require('playwright'),{spawn}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const checks=[],ok=(name,value)=>{assert(value,name);checks.push(name);};
(async()=>{
 const port=4387,server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port)}});await new Promise(r=>server.stdout.once('data',r));let browser;
 try{
  browser=await chromium.launch({headless:true,executablePath:process.env.PROWAY_CHROME});const context=await browser.newContext({viewport:{width:390,height:1100},acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://localhost:'+port);await page.locator('[data-action="new-order"]').waitFor();
  async function saved(){await page.waitForTimeout(250);return page.evaluate(()=>new Promise(resolve=>{const q=indexedDB.open('proway-pedidos',1);q.onsuccess=()=>{const db=q.result,r=db.transaction('snapshots').objectStore('snapshots').get('current');r.onsuccess=()=>{resolve(r.result.state);db.close();};};}));}
  const state=await saved();state.orders[0].name='Prueba de actualización';state.orders[0].showVat=false;state.orders[0].rows=[{id:1,product:'Butarga',size:'M',cut:'Hombre',qty:3,printed:'Prueba A',color:'Rojo',design:'Base',placement:'Texto en espalda',special:''},{id:2,product:'Playera',size:'M',cut:'Mujer',qty:2,printed:'Prueba B',color:'Azul',design:'Base',placement:'',special:''},{id:3,product:'Short',size:'CH',cut:'Hombre',qty:1,printed:'',color:'Rojo',design:'Base',placement:'',special:''}];
  state.rates=[{product:'Butarga',size:'M',cut:'Hombre',cost:100},{product:'Playera',size:'M',cut:'Mujer',cost:70}];state.shortCosts={CH:[60,40]};state.orders[0].advance=100;state.orders[0].advanceDate='2026-10-08';
  await page.locator('[data-action="open-backup"]').click();await page.locator('#pia-restore-file').setInputFiles({name:'previous-version.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(state))});await page.locator('[data-action="restore-data"]').click();
  ok('Restoring a previous-version workspace preserves all five orders',(await saved()).orders.length===5);
  await page.locator('[data-screen="tablas"]').click();await page.locator('[data-table="proveedor"]').click();ok('Supplier bill excludes fabric and shows sublimation 480',(await page.locator('#pia-supplier-sub').innerText()).includes('480.00'));ok('Cutting is separate and totals 60',(await page.locator('#pia-supplier-cut').innerText()).includes('60.00'));
  async function extra(type,product,qty,cutting){await page.locator('#pia-extra-form [name=type]').selectOption(type);await page.locator('#pia-extra-form [name=product]').selectOption(product);await page.locator('#pia-extra-form [name=size]').selectOption('M');await page.locator('#pia-extra-form [name=cut]').selectOption(product==='Playera'?'Mujer':'Hombre');await page.locator('#pia-extra-form [name=qty]').fill(String(qty));await page.locator('#pia-extra-form [name=cutting]').setChecked(cutting);await page.locator('#pia-extra-form button').click();}
  await extra('Error','Butarga',2,true);await extra('Impresión extra','Playera',1,false);ok('Extra impressions use the existing rate and optional cutting',(await page.locator('#pia-supplier-total').innerText()).includes('830.00'));ok('Reprints do not increase the client garment count',(await saved()).orders[0].rows.reduce((s,x)=>s+x.qty,0)===6);
  await page.locator('#pia-supplier-mode').selectOption('added');ok('Supplier IVA is optional and computes 962.80',(await page.locator('#pia-supplier-total').innerText()).includes('962.80'));
  await page.locator('[data-action="supplier-preview"]').click();await page.locator('[data-format="excel"]').click();const wait=page.waitForEvent('download');await page.locator('[data-action="run-export"]').click();const download=await wait;await download.saveAs(path.join(out,'supplier.xlsx'));
  const bytes=Array.from(fs.readFileSync(path.join(out,'supplier.xlsx')));const formulas=await page.evaluate(async bytes=>{const wb=new ExcelJS.Workbook();await wb.xlsx.load(new Uint8Array(bytes));const s=wb.getWorksheet('Documento');return [...Array(s.rowCount)].flatMap((_,i)=>s.getRow(i+1).values).filter(x=>x&&typeof x==='object'&&x.formula).map(x=>x.formula);},bytes);ok('Editable supplier Excel recalculates quantities, rates, IVA and total',formulas.some(x=>x.includes('E6*F6'))&&formulas.some(x=>x.includes('1.16')));
  await page.locator('[data-action="close-document"]').click();await page.locator('[data-screen="pedido"]').click();await page.locator('summary').filter({hasText:'Diseños rápidos'}).click();await page.locator('[data-design-use="rojo"]').click();await page.waitForTimeout(400);let current=await saved();ok('The red design supplies local front and back images',current.orders[0].images.front.startsWith('data:image/png')&&current.orders[0].images.back.startsWith('data:image/png'));ok('Choosing a new design requires renewed approval',!current.orders[0].designOk&&!current.orders[0].startDate);
  await page.locator('[data-screen="cobro"]').click();await page.locator('[data-action="preview-document"]').click();ok('Compact customer quote shows total, deposit and balance',(await page.locator('.pia-quote-modern').innerText()).includes('Saldo a pagar')&&!(await page.locator('.pia-quote-modern').innerText()).includes('IVA'));const pdfWait=page.waitForEvent('download');await page.locator('[data-action="run-export"]').click();await(await pdfWait).saveAs(path.join(out,'compact-quote.pdf'));await page.screenshot({path:path.join(out,'compact-quote-mobile.png'),fullPage:true});
  await page.locator('[data-action="close-document"]').click();await page.locator('#pia-payer-type').selectOption('PM');await page.locator('[data-action="preview-document"]').click();ok('A corporate client can hide IVA detail while retaining the net payment',!(await page.locator('.pia-quote-modern').innerText()).includes('IVA')&&(await page.locator('.pia-quote-modern').innerText()).includes('Neto a pagar'));await page.locator('[data-action="close-document"]').click();await page.locator('#pia-show-vat').check();await page.locator('[data-action="preview-document"]').click();ok('IVA detail can be enabled for the same quote',(await page.locator('.pia-quote-modern').innerText()).includes('IVA · 16%'));
  await page.emulateMedia({colorScheme:'dark'});ok('The application remains in the requested light theme',await page.locator('html').evaluate(x=>getComputedStyle(x).colorScheme)==='light');
  await page.locator('[data-action="close-document"]').click();await page.locator('[data-screen="taller"]').click();await page.locator('[data-work="costura"]').click();await page.locator('summary').filter({hasText:'Listado final'}).click();ok('Armado has the complete printable names and placement instructions',(await page.locator('#pia-main').innerText()).includes('Texto en espalda'));
  await page.reload();await page.locator('[data-action="new-order"]').waitFor();current=await saved();ok('Restart preserves original orders, both design views and reprint entries',current.orders[0].rows.length===3&&current.orders[0].supplier.extras.length===2&&current.orders[0].images.back);
  ok('New features raise no browser errors',errors.length===0);fs.writeFileSync(path.join(out,'upgrade-checks.json'),JSON.stringify({passed:checks.length,checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));
 }finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
